### ISSUE TITLE
Release notes has bad link to Docs

### ISSUE THREAD

**Issue by jonaspetersorensen** [adafruit/Adafruit_CircuitPython_HTTPServer#65]
Example from release notes 4.2.0:
```text
 Read the [docs](http://circuitpython.readthedocs.io/projects/HTTPServer/en/latest/) for info on how to use it.
 ```
That URL leads to 404.
I guess it should be https://docs.circuitpython.org/projects/httpserver/en/latest/api.html ?

**Comment by FoamyGuy** [comment]
Thank you for mentioning that. 

It appears that the server / URL is case sensitive it currently contains some upper case characters like `HTTPServer` but in the URL those seem to be causing trouble. The lower case variation of it's name does work successfully: `https://docs.circuitpython.org/projects/httpserver/en/latest/` - https://docs.circuitpython.org/projects/httpserver/en/latest/


I am a little weary about changing it in the release notes. I believe I've witnessed a problem in the past where changing information in the release can cause the release actions to get triggered again, which is problematic because there are some scripts within it that make the assumption that the newly released version will be larger than all prior version numbers. If the actions run on the same version as before that assumption isn't true and has caused weirdness in the case I've seen.

I'll make sure to adjust the docs link for the next release though, we can keep this issue open until then as a reminder.

**Comment by FoamyGuy** [comment]
fixed with the latest release.
