### ISSUE TITLE
CircuitPython 9.0.0 will require SO.REUSEADDR for socket reuse

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_HTTPServer#83]
CircuitPython 9.0.0-beta.1 will include this PR:
- https://github.com/adafruit/circuitpython/pull/8940

This makes the semantics of socket reuse as it is in CPython. One would need to use `socket.setsockopt(pool.SOL_SOCKET, pool.SO_REUSEADDR, 1)` in the same cases one would use it in CPython.

**HTTPServer maintainers:** Is this a breaking change for use of `adafruit_httpserver` or for the examples? Thanks for looking.

**Comment by michalpokusa** [comment]
Tested on ESP32-S2 with lates `adafruit_httpserver` and CP 9.0.0-beta.1.

Indeed starting the server, Ctrl-C'ing and Ctrl-D'ing results in EADDRINUSE. Modyfying code lib code so it calls the line you provided solves the problem.

Changing the port to different one and re-launching the code works too, but this is more of a hack than solution.
 
![image](https://github.com/adafruit/Adafruit_CircuitPython_HTTPServer/assets/72110769/3b68c69f-1d8b-4c21-8b99-3f6a2565699f)

One thing I noticed is that the error is also present when trying to use port 80, probably because web workflow uses it too. It was possible to use this port before, so examples would have to be cahnged to use e.g. 8000. I can change them and add note to docs about this behaviour.
